---
- name: Pause until SSH
  pause:
    seconds: 200
- name: Run apt-get update
  command: apt-get update
  become: yes

- name: Upgrade all packages to the latest version
  shell: sudo apt-get -f install

- name: Install above defined dependencies
  apt: name={{ item }} state=present
  with_items: 
    - git
    - mongodb
    - python3-pip
    - nginx
    - nodejs-legacy
    - npm
  become: yes

- name: Run apt-get update
  command: apt-get update
  become: yes

- name: Clone checkbox.io repo - canary
  git: 
    repo: 'https://github.com/sambhavjain204/checkbox.io.git'
    dest: /home/ubuntu/checkboxio/.
    version: canary
# - name: Clone checkbox.io repo
#   git: 
#     repo: "https://{{ lookup('env', 'GIT_USER') }}:{{ lookup('env', 'GIT_TOKEN') }}@github.com/chrisparnin/checkbox.io.git"
#     dest: "checkboxio/."

- name: Install pymongo
  pip: name=pymongo state=latest use_mirrors=no
  become: yes

- name: Install forever
  npm: name=forever global=yes state=present
  become: yes

- name: Transfer all environment variables to the VM
  blockinfile:
    path: /etc/environment
    block: |
      MONGO_PORT="{{lookup('env', 'MONGO_PORT')}}"
      MONGO_IP="{{lookup('env', 'MONGO_IP')}}"
      MONGO_USER="{{lookup('env', 'MONGO_USER')}}"
      MONGO_PASSWORD="{{lookup('env', 'MONGO_PASSWORD')}}"
      MAIL_USER="{{lookup('env', 'MAIL_USER')}}"
      MAIL_PASSWORD="{{lookup('env', 'MAIL_PASSWORD')}}"
      MAIL_SMTP="{{lookup('env', 'MAIL_SMTP')}}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes

- name: Create database user
  mongodb_user:
    database: admin              
    name: "{{lookup('env', 'MONGO_USER')}}"
    password: "{{lookup('env', 'MONGO_PASSWORD')}}"
    roles: readWriteAnyDatabase
    state: present
  become: yes

- name: Change default nginx file
  become: yes
  replace:
    path: /home/ubuntu/checkboxio/local-conf/default
    regexp: '^  root /Users/gameweld/bitbucket/checkbox.io/checkbox.io/public_html/;$'
    replace: '  root /home/ubuntu/checkboxio/public_html/;'

- name: Copy nginx default file
  become: yes
  command: cp /home/ubuntu/checkboxio/local-conf/default /etc/nginx/sites-enabled/default

# - name: Change nginx.conf file
#   become: yes
#   replace:
#     path: ./checkboxio/local-conf/nginx.conf
#     regexp: '^         include /etc/nginx/sites-available/*;$'
#     replace: '         include /etc/nginx/sites-enabled/*;$'

# - name: Copy nginx default file
#   copy:
#     src: ./checkboxio/local-conf/default
#     dest: /etc/nginx/sites-enabled/default
#     remote_src: yes
#   become: yes

# - name: Copy nginx config file
#   copy:
#     src: ./checkboxio/local-conf/nginx.conf
#     dest: /etc/nginx/nginx.conf
#     remote_src: yes
#   become: yes

- name: Copy nginx config file
  become: yes
  command: cp /home/ubuntu/checkboxio/local-conf/nginx.conf /etc/nginx/nginx.conf

# - name: Edit path to public_html in nginx default file
#   replace:
#     path: /etc/nginx/sites-enabled/default
#     regexp: '^  root /Users/gameweld/bitbucket/checkbox.io/checkbox.io/public_html/;$'
#     replace: '  root ../checkboxio/public_html/;'
#   become: yes

- name: Restart nginx
  service: name=nginx state=restarted
  become: yes

# - name: npm install
#   command: chdir=./checkboxio/server-side/site npm install
#   become: yes

- name: Install packages based on package.json.
  npm:
    path: /home/ubuntu/checkboxio/server-side/site
  become: yes

- name: Checking if any nodejs apps are running
  command: forever list
  register: forever_running_apps
  changed_when: false
  become: yes

- name: Start checkboxio app
  command: forever start -o out.log -e err.log  server.js
  become: yes
  args:
    chdir: /home/ubuntu/checkboxio/server-side/site/
  when: "forever_running_apps.stdout.find('/home/ubuntu/checkboxio/server-side/site/server.js') == -1"
