---
- name: Run apt-get update
  command: apt-get update
  become: yes

- name: Install NPM
  apt:
    pkg: npm
    state: present
  become: yes

- name: Run apt-get update
  command: apt-get update
  become: yes

- name: Create checkbox job
  command: jenkins-jobs --conf /home/ubuntu/Devops_Milestone1/jenkins_jobs.ini update /home/ubuntu/Devops_Milestone1/Checkboxio/roles/CreateCheckboxJob/files/createjob.yaml
  become: yes