- name: Run apt-get update
  command: apt-get update
  become: yes

- name: Install Prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - maven
    - build-essential
    - libmysqlclient-dev
  become: yes

- name: Run apt-get update
  command: apt-get update
  become: yes

- name: "Install Necessary JDK packages"
  apt: package="{{item}}" state="present"
  become: yes
  with_items:
    - python-software-properties 
    - debconf-utils

- name: Run apt-get update
  command: apt-get update
  become: yes

- name: Adding apt-key for the JDK
  shell: add-apt-repository ppa:webupd8team/java
  become: yes

- name: Run apt-get update
  command: apt-get update
  become: yes

- name: Accept licenses automatically
  shell: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
  become: yes

- name: Install java 8
  apt: package="oracle-java8-installer" state="present"
  become: yes